# Generated by Django 3.2.2 on 2021-05-13 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fullname',
            new_name='username',
        ),
    ]
