# Generated by Django 3.2.2 on 2021-05-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('source', models.CharField(max_length=30)),
                ('destination', models.CharField(max_length=50)),
                ('flight_name', models.CharField(max_length=50)),
                ('flight_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('duration', models.CharField(max_length=30)),
                ('departure', models.CharField(max_length=50)),
                ('arrival', models.CharField(max_length=50)),
                ('via', models.CharField(max_length=32)),
            ],
        ),
    ]
