# Generated by Django 3.2.2 on 2021-05-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module2', '0002_flight_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('check', models.IntegerField()),
                ('unchecked', models.IntegerField()),
                ('img', models.CharField(max_length=500)),
            ],
        ),
    ]
