# Generated by Django 3.2.2 on 2021-05-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module2', '0003_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='city',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
