# Generated by Django 3.2.3 on 2021-05-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module2', '0004_hotel_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
