# Generated by Django 3.2.3 on 2021-05-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module2', '0005_hotel_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveFlight',
            fields=[
                ('cardno', models.CharField(max_length=30)),
                ('uname', models.CharField(max_length=30)),
                ('source', models.CharField(max_length=30)),
                ('destination', models.CharField(max_length=50)),
                ('flight_name', models.CharField(max_length=50)),
                ('flight_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('duration', models.CharField(max_length=30)),
                ('departure', models.CharField(max_length=50)),
                ('arrival', models.CharField(max_length=50)),
                ('via', models.CharField(max_length=32)),
                ('price', models.IntegerField(null=True)),
                ('seats', models.IntegerField(null=True)),
                ('totalprice', models.IntegerField(null=True)),
            ],
        ),
    ]
