# Generated by Django 3.2.3 on 2021-05-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module2', '0006_saveflight'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardno', models.CharField(max_length=30)),
                ('uname', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30, null=True)),
                ('name', models.CharField(max_length=300)),
                ('img', models.CharField(max_length=500)),
                ('price', models.IntegerField(null=True)),
                ('rooms', models.IntegerField(null=True)),
                ('totalprice', models.IntegerField(null=True)),
            ],
        ),
    ]
